codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_not_found: success
        informational: true
    patch:
      default:
        target: 50% # The coverage target for the new code in pull requests

  ignore:
    - "types/*"
    - "models/*"
